name: Build TTLock APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      BUILDZER_ALWAYS_YES: 1          # 自动回答 root 警告
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer (Docker)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            kivy/buildozer \
            buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ttlockroot-apk
          path: bin/*.apk
